spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: local

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJwtThatIsAtLeast32CharactersLong}
  access-expiration: 900000
  refresh-expiration: 604800000